### ISSUE TITLE
Config option to remove K8s resource limit for all/selected services

### ISSUE THREAD

**Issue by NickVolynkin** [cozystack/cozystack#1118]
Since v0.32.0 (https://github.com/cozystack/cozystack/pull/972 and https://github.com/cozystack/cozystack/pull/1025) resource configuration has changed from explicit requests and limits to one configuration, which defines both requests and limits.

Let's assume a `cpu-allocation-ratio` of 10, as per default.

```yaml
resources:
   cpu: 1   # equals 1000m
   # actual request: 100m
   # actual limit:   1000m
```

There are cases where services should not have resource limits, at least for CPU, such as for production workloads.

```yaml
resources:
   cpu: 1   # equals 1000m
   # actual request: 100m
   # actual limit:   none
```
