### ISSUE TITLE
Automatically remove `flannel` and `kube-proxy`

### ISSUE THREAD

**Issue by kvaps** [cozystack/cozystack#2]
Talos automatically setups flannel and kube-proxy, and even if you switch config to:

```
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
```

it will not automatically remove it. User have to run:

```
kubectl delete -n kube-system ds kube-flannel
kubectl delete -n kube-system  ds kube-proxy
```

Let's think how we can automate it

**Comment by NickVolynkin** [comment]
We discussed it and decided to try fixing it upstream.

**Comment by lllamnyp** [comment]
We need to check that the problem persists and if so, file an issue in upstream.

**Comment by lllamnyp** [comment]
Talos is mostly behaving as intended. It appears that the backend for this is from kubeadm. Since this snippet

```yaml
cluster:
  network:
    cni:
      name: none
  proxy:
    disabled: true
```

is part of a bootstrap config, it was never intended to be "re-applied", so Talos does not and probably cannot track which objects are related to an application of this configuration and which daemonset should be deleted when a configuration with  `cluster.cni.name==none` is applied: was the previous cni flannel or calico? The configuration is declarative, state is not tracked, so there is no way to know the "before".

We should make it abundantly clear in the documentation that if the user has an already running kubernetes cluster, perhaps bootstrapped with Talos, they should delete any existing CNI and get rid of kube-proxy, before proceeding to install cozystack.
