### ISSUE TITLE
Rolling update for Talos nodes

### ISSUE THREAD

**Issue by kvaps** [cozystack/cozystack#20]
During cluster setup user have to upload `secrets.yaml` and `cluster.conf` into Kubernetes. eg:

```bash
kubectl create secret generic -n cozy-system cozy-talos-bootstrap --from-file secrets.yaml --from-file cluster.conf
```

This will start a reconcilation controller, which checks all the nodes in a cluster, and performs their rolling update:

```bash
talosctl -e <node_address> -n <node_address> upgrade --preserve=<true|false> -i <image>
```

During the upgrade talos config on the node should also be updated to contain the new image.
In talos-bootstrap script we usually do that immediately [before](https://github.com/aenix-io/talos-bootstrap/blob/85894f9a06766d6b4753a34511df04cfe09fc218/talos-bootstrap#L350) the update operation.

**Comment by kvaps** [comment]
I think we need to introduce a new resource:

```
apiVersion: cozystack.io/v1alpha1
kind: TalosNode
metadata:
  name: srv1
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: srv1
    uid: d7ba2238-d45a-4edc-a348-aa5157afc730
spec:
  image: ghcr.io/aenix-io/cozystack/installer:v0.0.2
status:
  image: ghcr.io/aenix-io/cozystack/installer:v0.0.2
```
