### ISSUE TITLE
enhancement: add proper default values for install and retries for HelmCharts

### ISSUE THREAD

**Issue by gecube** [cozystack/cozystack#214]
Hi!

Today I observed the situation when HelmRelease for tenant kubernetes cluster was stuck. There is a good documentation for remediation of HelmReleases here: https://fluxcd.io/flux/components/helm/helmreleases/#configuring-failure-handling

But to make the process smoother and cleaner I am proposing to add 
```yaml
          install:
            remediation:
              retries: 3
          upgrade:
            remediation:
              retries: 3
```

to every HelmRelease inside of cozystack. These settings are sane and provides better experience for DevOps engineers
