### ISSUE TITLE
Option to configure registry-mirrors for tenant clusters

### ISSUE THREAD

**Issue by kvaps** [cozystack/cozystack#286]

**Comment by gecube** [comment]
What is the use case? I'd prefer to have a dedicated harbor instance in main cluster and configure all tenants cluster to pull all images through this main harbor BY DEFAULT... What do you think?

**Comment by kvaps** [comment]
Sounds interesting, let's consider global option for this

**Comment by NickVolynkin** [comment]
Related issue: https://github.com/cozystack/cozystack/issues/173

**Comment by NickVolynkin** [comment]
Users can explicitly configure Cozystack to use Google Container Registry:
https://cozystack.io/docs/operations/talos/configuration/talos-bootstrap/#preparation

```yaml
  registries:
    mirrors:
      docker.io:
        endpoints:
        - https://mirror.gcr.io
```
