### ISSUE TITLE
Incorrect selector (app: kube-rbac-proxy) causes false etcd alerts in VictoriaMetrics monitoring

### ISSUE THREAD

**Issue by Identitry** [cozystack/cozystack#789]
**Description:**
By default, CozyStack deploys an etcd monitoring VMPodScrape with a pod selector that uses the label:
```yaml
selector:
  matchLabels:
    app: kube-rbac-proxy
```

This selector is overly generic and doesn’t target the actual etcd pods. Instead, it selects unrelated proxy pods, resulting in continuous false-positive alerts such as: 
- etcdMembersDown: etcd cluster "cozy-monitoring/etcd-managment-scrape": members are down (1).
- etcd cluster "cozy-monitoring/etcd-managment-scrape": insufficient members (0).

...even though the real etcd cluster pods are healthy and running normally.

**Expected behavior:**
The default VMPodScrape should specifically target actual etcd pods, for example:

```yaml
selector:
  matchLabels:
    app.kubernetes.io/name: etcd
```

or document explicitly that users must manually adjust this selector to match their actual etcd pods.

**Current workaround:**
Manually editing the VMPodScrape selector to use the correct label.
