### ISSUE TITLE
Dashboard valuesOverride field serializes YAML incorrectly as a string

### ISSUE THREAD

**Issue by Identitry** [cozystack/cozystack#892]
With limited knowledge of Kubernetes/Cosystack inner workings and lack of documentation I've been doing my best to try and create a cluster in an instance and initialise it with Flux using the Dashboard but failed on this, sure I can probably use the yaml-editor but still haven't been able to find out what the right way is to initialise Flux in the new cluster (I assume I can add the sync object to the FluxInstance using valuesOverride?). Anyway, there seems to be a problem with how valuesOverride is handled from the Dashboard.

**Description:**
When trying to configure addons.fluxcd.valuesOverride via the Cozystack dashboard (Helm values editor), the input is serialized incorrectly.

Even if valid YAML is provided, the dashboard wraps it in quotes ("...") and inserts backslashes (\) — making the valuesOverride a string, not an object as expected by the FluxInstance operator.

This causes Flux CD bootstrapping or GitRepository sync configuration to fail.

**Steps to Reproduce:**
1. Go to the Dashboard.
2. Create a Kaubernets instance.
3. In addons.fluxcd.valuesOverride, paste valid YAML, such as:

```yaml
sync:
  kind: GitRepository
  url: https://github.com/user/git-ops.git
  ref: refs/heads/main
  path: kubernetes/tenant-prod
  interval: 1m
```

4. Open yaml-editor and observe that the YAML is automatically converted into a string:

```yaml
## Flux CD
  ##
  fluxcd:
    ## @param addons.fluxcd.enabled Enables Flux CD
    ## @param addons.fluxcd.valuesOverride Custom values to override
    ##
    enabled: true
    valuesOverride: "sync:

      \  kind: GitRepository

      \  url: https://github.com/user/git-ops.git

      \  ref: refs/heads/main

      \  path: kubernetes/tenant-prod

      \  interval: 1m"
```

5. Result: Error message in dashboard: An error occurred: The given values don't match the required format. The following errors were found: - /addons/fluxcd/valuesOverride: must be object.

**Expected Behavior:**
- The dashboard should allow structured YAML as a proper object.
- valuesOverride must remain a YAML object, not stringified.
- Alternatively, add proper support for multi-line YAML input without quoting.

**Environment Info:**
- Cozystack version: 0.30.4
- Kubernetes package version: 0.18.1

**Workaround:**
- Manually edit the object using dashboard yaml editor.

**Additional Comment:**
You really seems to have something great going on but without proper documentation it is really hard trying to adopt it...
