### ISSUE TITLE
Improve flexibility of OIDC configuration (issuer URL, clientID, optional internal Keycloak)

### ISSUE THREAD

**Issue by LikeMySoul** [cozystack/cozystack#902]
Hello,

While configuring OIDC authentication, we encountered a few hardcoded behaviors inside the Keycloak integration, which currently limit flexibility in some scenarios.

Specifically:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeapps-auth-config
  namespace: cozy-dashboard
data:
  values.yaml: |
    kubeapps:
      authProxy:
        enabled: true
        provider: "oidc"
        clientID: "kubeapps"
        clientSecret: {{ $kubeappsClient }}
        cookieSecret: {{ $cookieSecret }}
        extraFlags:
          - --ssl-insecure-skip-verify
          - --cookie-secure=false
          - --scope=openid email groups
          - --oidc-issuer-url=https://keycloak.{{ $host }}/realms/cozy
```

### Current limitations observed:

- The oidc-issuer-url is hardcoded to a specific domain and realm, making it difficult to integrate with custom OIDC providers.
- The clientID is fixed to kubeapps, without an option to override it via existing secret.
- There seems to be no documented option to disable the internal Keycloak server when an external OIDC provider is preferred.

### Suggestion:

- To improve flexibility, it would be great if:
- Both oidc-issuer-url and clientID could be exposed as configurable parameters via existing secret.
- An option could be added to disable the built-in Keycloak server while retaining OIDC authentication support.
- This would allow broader use cases and easier integration with existing infrastructure.

Thank you for your great work and consideration of this improvement!
